FROM strapi/base
WORKDIR /srv/app
COPY --chown=1000:1000 ./app/package.json ./
COPY --chown=1000:1000 ./app/yarn.lock ./
USER 1000
RUN yarn install
COPY --chown=1000:1000 ./app .
ENV NODE_ENV production
ENV DATABASE_CLIENT=mysql 
ENV DATABASE_NAME=strapi
ENV DATABASE_HOST=strapi-db
ENV DATABASE_PORT=3306
ENV DATABASE_USERNAME=strapi
ENV DATABASE_PASSWORD=strapi
RUN yarn build
EXPOSE 1337
CMD ["yarn", "start"]