version: '3'
services:
  strapi-db:
    image: joellord/strapi-db
    networks:
      - strapi
  strapi-back:
    image: joellord/strapi-back
    ports:
      - '1337:1337'
    networks:
      - strapi
  strapi-front:
    image: joellord/strapi-front
    ports: 
      - '8080:80'
    environment:
      BASE_URL: http://localhost:1337
networks:
  strapi: