FROM bitnami/postgresql:12
ENV POSTGRES_DB=strapi
ENV POSTGRES_USER=strapi
ENV POSTGRES_PASSWORD=strapi
COPY ./db.sql /docker-entrypoint-initdb.d/db.sql
# COPY ./db.sql /tmp/db.sql
# RUN mkdir temp
# RUN groupadd non-root-postgres-group
# RUN useradd non-root-postgres-user --group non-root-postgres-group
# RUN chown -R non-root-postgres-user:non-root-postgres-group /temp
# RUN chmod 777 /temp
# USER non-root-postgres